---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
```

```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
```

```{r}
typeof(studentMajors)
levels(studentMajors)
as.integer(studentMajors)
studentMajors
```
```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算

trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
trueInteger
```

```{r}
library(lubridate)
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
library(lubridate)
dtObject<-ymd_hms("1970-11-01 00:02:53") 
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
dtObjectVector
```

```{r}
class(dtObject)
dtObject
class(dtObjectVector)
```
```{r}
Sys.timezone()
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
twDateTime
LisbonDateTime
```
```{r}
as.integer(ymd("1970-01-01"))
as.integer(ymd("1970-01-02"))
as.integer(ymd("2019-03-11"))
```

