---
title: '2019-04-24'
author: "Alice"
date: "4/24/2019"
output: html_document
---

```{r}
a <- matrix(c(1:6), nrow=3, ncol=2)
a
```

```{r}
m2<-matrix(c("a","b","c","d"),2,2)
class(m2)
typeof(m2)
a<-m2[[1]]
c<-m2[[3]]
bd<-m2[2,]
a
c
bd
```

```{r}
MAT2 <- matrix(c("a","b","c","d"),2,2)
MAT2
class(MAT2)
typeof(MAT2)
MAT2[[2]]
MAT2[c(T,F,F,T)]
```
```{r}
StuDF <- list(StuID=c(1,2,3,4,5), ##欄位名稱=欄位值
                  name=c("小明","大雄","胖虎","小新","大白"),
                  score=c(80,60,90,70,50))
StuDF 
```
```{r}
StuDF <- data.frame(StuID=c(1,2,3,4,5), ##欄位名稱=欄位值
                  name=c("小明","大雄","胖虎","小新","大白"),
                  score=c(80,60,90,70,50))
StuDF 
StuDF[[2]][[3]]
```
```{r}
StuDF[[2]][[3]]
```

```{r}
str(StuDF) 
```

```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
class(StuDF$姓名)
```
```{r}
StuDF$姓名 <- as.character(StuDF$姓名)
class(StuDF$姓名)
```
```{r}
class(StuList)
as.data.frame(StuList) -> StuDF3

class(StuDF3)
StuDF3
```

```{r}
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
class(StuDF4)
StuDF4
```

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```
```{r}
chosenLETTERS <- LETTERS[1:15]
matObj1 <- matrix(chosenLETTERS,5,3)
matObj1
```
```{r}
chosenLETTERS[8]
matObj1[8]
matObj1
matObj1[3,2] 
matObj1[c(F,F,TRUE,F,F),c(F,TRUE,F)]
matObj1[,3]
```

```{r}
cbind(matObj1,letters[1:5])
```

```{r}
matObj1[c(T,F,F,T,F),c(F,T,T)]
matObj1[c(1,4),c(2,3)]
```
```{r}
LETTERS
chosenLETTERS <- LETTERS[1:8]
m <- matrix(chosenLETTERS,2,4)
m
tolower(m) # 轉成小寫
m
toupper(m) # 轉成大寫
m
```

