---
title: "Untitled"
author: "Alice"
date: "2019年6月5日"
output: html_document
---

```{r}
a <- 2
a
`a`
```
```{r}
b<-"你好"
bVector<-c("你好","How are you?")
class(b)
class(bVector)
```
```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```
```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
# 加總向量內的所有元素值。
sum(aLogical)
```
```{r}
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
class(a+bL)
class(aL+bL)
class(aL*bL)
class(a*bL)
class(aL-bL)
class(a-bL)
```
```{r}
c <- 4
c+a
a^b
a %% b
```
```{r}
startingDate <- ymd("2000-02-17")
startingDate
startingDate + years(1)
startingDate + dyears(1)

ymd("2000-02-01") -> startingDate
ymd("2019-08-11") -> endingDate
endingDate - startingDate
```
```{r}
course <- c("個體經濟學","投資學","總體經濟學")
str_subset(course,"經濟學")
str_detect(course,"經濟學")
```
```{r}
a<-c(1:3)
typeof(a)
a
```
```{r}
aWithNames <- c(a1=1,a2=2,a3=3)
typeof(a)
aWithNames
```
```{r}
sample(99:103,15,replace = T)-> yy
sample(1:12,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates
twDates
```
```{r}
str_replace(twDates,"民國","") -> twDates2
str_replace(twDates2,"月","") -> twDates2  
twDates2
```

